actor/urls.py
from django.urls import path
from . import views

app_name = 'actor'

urlpatterns = [
    path('add', views.actor_add, name='add'),
    path('details/<int:actor_index>', views.actor_detail, name='details'),
    path('edit/<int:actor_index>', views.actor_edit, name='edit'),
    path('delete/<int:actor_index>', views.actor_delete, name='delete'),
    path('', views.actor_list, name='list'),
]

director/api/v1/urls.py
from django.urls import path
from . import views

app_name = 'movie-rest-v1'

urlpatterns = [
    path('', views.movie_home, name = 'list'),
    path('<int:movie_id>', views.movie_detail, name = 'details'),
    path('generics', views.MovieHome.as_view(), name = 'generics-list'),
    path('create', views.movie_create, name = 'create'),
    path('update/<int:movie_id>', views.movie_update, name = 'update'),
    path('delete/<int:movie_id>', views.movie_delete, name = 'delete'),
]

director/urls.py
from django.urls import path
from . import views

app_name = 'director'

urlpatterns = [
    path('add', views.director_add, name='add'),
    path('details/<int:director_index>', views.director_detail, name='details'),
    path('edit/<int:director_index>', views.director_edit, name='edit'),
    path('delete/<int:director_index>', views.director_delete, name='delete'),
    path('', views.director_list, name='list'),
]

director/models.py
from django.db import models


class Movie(models.Model):
    name = models.CharField(verbose_name='Movie Name', max_length=50)
    production_year = models.PositiveIntegerField(default=1900)
    director = models.ForeignKey('director',on_delete=models.CASCADE, null=True)
    actors = models.ManyToManyField('actor.actor',related_name='movies')
    creation_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Director(models.Model):
    GENDERS = (
        ('m', 'Male'),
        ('f', 'Female'),
    )

    name = models.CharField(verbose_name='Director', max_length=50)
    gender = models.CharField(choices=GENDERS, max_length=6, default='m')

    def __str__(self):
        return self.name

director/forms.py
from django.forms import ModelForm
from .models import Director


class DirectorForm(ModelForm):
    class Meta:
        model = Director
        fields = '__all__'

    def my_custom_style():
        pass

director/api/v1/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view, authentication_classes, permission_classes, action
from rest_framework.permissions import IsAuthenticated, AllowAny, IsAuthenticatedOrReadOnly, IsAdminUser
from rest_framework.authentication import TokenAuthentication
from rest_framework.generics import ListAPIView, UpdateAPIView, ListCreateAPIView
from director.api.v1.serializers import MovieSerializer, MovieCreateSerializer
from director.models import Movie
from .permissions import DeveloperPermission
from django.contrib.auth.decorators import permission_required


@api_view(['GET'])
def movie_home(request):
    movie_objects = Movie.objects.all()
    serializer = MovieSerializer(movie_objects, many=True)
    return Response(data=serializer.data, status=status.HTTP_200_OK)


class MovieHome(ListAPIView):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer


@api_view(['GET'])
def movie_detail(request, movie_id):
    movie_object = Movie.objects.get(pk=movie_id)
    serializer = MovieSerializer(movie_object)
    return Response(data=serializer.data, status=status.HTTP_200_OK)


def movie_create(request):
    response = {'data': {}, 'status': status.HTTP_400_BAD_REQUEST}
    serializer = MovieCreateSerializer(data=request.data)

    if serializer.is_valid():
        serializer.save()
        response['data'] = serializer.data
        response['status'] = status.HTTP_201_CREATED

    else:
        response['data'] = serializer.errors
        response['status'] = status.HTTP_400_BAD_REQUEST

    return Response(**response)


@api_view(['PUT','PATCH'])
@authentication_classes([TokenAuthentication])
@permission_classes([DeveloperPermission])
def movie_update(request, movie_id):
    response = {'data': {}, 'status': status.HTTP_400_BAD_REQUEST}
    movie_instance = Movie.objects.get(pk=movie_id)
    if request.method == 'PUT':
        serializer = MovieSerializer(
            instance=movie_instance, data=request.data)
    else:
        serializer = MovieSerializer(
            instance=movie_instance, data=request.data, partial=True)

    if serializer.is_valid():
        serializer.save()
        response['data'] = serializer.data
        response['status'] = status.HTTP_201_CREATED

    else:
        response['data'] = serializer.errors
        response['status'] = status.HTTP_400_BAD_REQUEST

    return Response(**response)


@api_view(['DELETE'])
def movie_delete(request, movie_id):
    Movie.objects.get(pk=movie_id).delete()
    return Response(data={'details': 'Movie deleted successfully'}, status=status.HTTP_204_NO_CONTENT)

director/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from django.http.response import JsonResponse
from django.contrib import messages
from .models import Director
from .forms import DirectorForm


def director_list(request):
    directors = Director.objects.all()
    return render(request, 'director/list.html', context={'directors': directors})


def director_add(request):
    if request.method == 'GET':
        form = DirectorForm()
        return render(request, template_name='director/add.html', context={'form': form})
    elif request.method == 'POST':
        form = DirectorForm(request.POST or None, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse('director:list'))


def director_detail(request, **kwargs):
    director_index = kwargs.get('director_index')
    director = Director.objects.get(id=director_index)
    return render(request, 'director/details.html', context={'director': director, 'director_index': director_index})


def director_edit(request, **kwargs):
    director_index = kwargs.get('director_index')
    director = Director.objects.get(id=director_index)
    if request.method == 'GET':
        form = DirectorForm(instance=director)
        return render(request, template_name='director/edit.html', context={'form': form, 'director': director})
    elif request.method == 'POST':
        form = DirectorForm(request.POST or None,
                         files=request.FILES, instance=director)
        if form.is_valid():
            form.save()
            return redirect(reverse('director:list'))


def director_delete(request, **kwargs):
    director_index = kwargs.get('director_index')
    director = Director.objects.get(id=director_index)
    director.delete()
    return redirect(reverse('director:list'))

director/templates/director/add.html
{% extends 'general_templates/base.html' %} {% load crispy_forms_tags %}
{% block body_content %}
<form
  class="d-flex flex-column mx-auto w-50"
  action="{% url 'director:add' %}"
  method="POST"
  enctype="multipart/form-data"
>
  <h2 class="text-center my-3">Add Director</h2>
  {% csrf_token %} {{form | crispy}}
  <button type="submit" class="btn btn-success align-self-start my-2">Create</button>
</form>

{% endblock %}

director/templates/director/details.html
{% extends 'general_templates/base.html' %} {% block body_content %}
<div class="delete_div d-flex flex-column">
  <div style="color: rgb(225, 225, 225)" class="text-center h3">
    Director Details.
  </div>
  <div class="w-50 m-auto">
    <img src="{{request.scheme}}://{{request.get_host}}{{director.profile_picture.url}}"/>
    <br/>
    <div style="color: rgb(225, 225, 225)" class="h5">
      Director ID : {{ director_index }}
    </div>
    <div style="color: rgb(225, 225, 225)" class="h5">
      Director Name : {{ director.name }}
    </div>
    <div style="color: rgb(225, 225, 225)" class="h5">
      Director Gender : {{ director.gender }}
    </div>
    <a class="btn btn-success my-2" href="{% url 'director:list' %}">Back Home</a>
  </div>
</div>

{% endblock %}

director/templates/director/edit.html
{% extends 'general_templates/base.html' %}
{% load crispy_forms_tags %}
{% block body_content %}
<form
  class="d-flex flex-column mx-auto w-50"
  action="{% url 'director:edit' director.id%}"
  method="POST"
  enctype="multipart/form-data"
>
  <h2 class="text-center my-3">Edit Director</h2>
  {% csrf_token %}
  {{form|crispy}}
  <div class="d-flex justify-content-between">
    <a class="btn btn-danger mt-4" href="{% url 'director:list' %}">Back Home</a>
    <button class="btn btn-success mt-4">Confirm Edit</button>
  </div>
</form>

{% endblock %}

director/templates/director/list.html
{% extends 'general_templates/base.html' %} {% block body_content %}
<div class="w-75 m-auto">
  {% if messages %} {% for message in messages %}
  <div class="alert alert-danger" role="alert">{{ message }}</div>
  {% endfor %} {% endif %}
  <div class="d-flex justify-content-center">
    <table class="table table-bordered table-dark">
      <thead>
        <tr>
          <th colspan="4" class="text-center h4">Directors</th>
        </tr>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Director Name</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      {% for director in directors %}
      <tr scope="row">
        <td>{{ director.id }}</td>
        <td>{{ director.name }}</td>
        <td>
          <a
            href="{% url 'director:details' director.id%}"
            class="btn btn-primary btn-sm mx-1 my-1"
          >
            Details
          </a>
          {% if request.user.is_authenticated %}
          <a
            href="{% url 'director:edit' director.id%}"
            class="btn btn-warning btn-sm mx-1 my-1"
          >
            Edit
          </a>
          <a
            href="{% url 'director:delete' director.id%}"
            class="btn btn-danger btn-sm mx-1 my-1"
          >
            Delete
          </a>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </table>
  </div>
  <div class="d-flex justify-content-end">
    <a class="btn btn-success btn-sm mx-1 my-1" href="{% url 'director:add' %}"
      >Add New Director</a
    >
  </div>
</div>
{% endblock %}