actor/api/v1/urls.py
from django.urls import path
from . import views

app_name = 'actor-rest-v1'

urlpatterns = [
    path('', views.actor_home, name = 'list'),
    path('<int:actor_id>', views.actor_detail, name = 'details'),
    path('generics', views.ActorHome.as_view(), name = 'generics-list'),
    path('create', views.actor_create, name = 'create'),
    path('update/<int:actor_id>', views.actor_update, name = 'update'),
    path('delete/<int:actor_id>', views.actor_delete, name = 'delete'),
]

actor/urls.py
from django.urls import path
from . import views

app_name = 'actor'

urlpatterns = [
    path('add', views.actor_add, name='add'),
    path('details/<int:actor_index>', views.actor_detail, name='details'),
    path('edit/<int:actor_index>', views.actor_edit, name='edit'),
    path('delete/<int:actor_index>', views.actor_delete, name='delete'),
    path('', views.actor_list, name='list'),
]

actor/models.py
from django.db import models


class Actor(models.Model):
    GENDERS = (
        ('m', 'Male'),
        ('f', 'Female'),
    )

    name = models.CharField(verbose_name='Actor', max_length=50)
    birth_date = models.PositiveIntegerField(default=1950)
    gender = models.CharField(choices=GENDERS, max_length=6, default='m')
    profile_picture = models.ImageField(upload_to='actor')

    def __str__(self):
        return self.name

actor/forms.py
from django.forms import ModelForm
from .models import Actor


class ActorForm(ModelForm):
    class Meta:
        model = Actor
        fields = '__all__'

    def my_custom_style():
        pass

actor/api/v1/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.permissions import IsAuthenticated, AllowAny, IsAuthenticatedOrReadOnly, IsAdminUser
from rest_framework.authentication import TokenAuthentication
from rest_framework.generics import ListAPIView, UpdateAPIView, ListCreateAPIView
from actor.api.v1.serializers import ActorSerializer, ActorCreateSerializer
from actor.models import Actor

from .permissions import DeveloperPermission


@api_view(['GET'])
def actor_home(request):
    actor_objects = Actor.objects.all()
    serializer = ActorSerializer(actor_objects, many=True)
    return Response(data=serializer.data, status=status.HTTP_200_OK)


class ActorHome(ListAPIView):
    queryset = Actor.objects.all()
    serializer_class = ActorSerializer


@api_view(['GET'])
def actor_detail(request, actor_id):
    actor_object = Actor.objects.get(pk=actor_id)
    serializer = ActorSerializer(actor_object)
    return Response(data=serializer.data, status=status.HTTP_200_OK)


@api_view(['POST'])
def actor_create(request):
    response = {'data': {}, 'status': status.HTTP_400_BAD_REQUEST}
    serializer = ActorCreateSerializer(data=request.data)

    if serializer.is_valid():
        serializer.save()
        response['data'] = serializer.data
        response['status'] = status.HTTP_201_CREATED

    else:
        response['data'] = serializer.errors
        response['status'] = status.HTTP_400_BAD_REQUEST

    return Response(**response)


@api_view(['PUT', 'PATCH'])
@authentication_classes([TokenAuthentication])
@permission_classes([IsAuthenticated, DeveloperPermission])
def actor_update(request, actor_id):
    response = {'data': {}, 'status': status.HTTP_400_BAD_REQUEST}
    actor_instance = Actor.objects.get(pk=actor_id)
    if request.method == 'PUT':
        serializer = ActorSerializer(
            instance=actor_instance, data=request.data)
    else:
        serializer = ActorSerializer(
            instance=actor_instance, data=request.data, partial=True)

    if serializer.is_valid():
        serializer.save()
        response['data'] = serializer.data
        response['status'] = status.HTTP_201_CREATED

    else:
        response['data'] = serializer.errors
        response['status'] = status.HTTP_400_BAD_REQUEST

    return Response(**response)


@api_view(['DELETE'])
def actor_delete(request, actor_id):
    Actor.objects.get(pk=actor_id).delete()
    return Response(data={'details': 'Actor deleted successfully'}, status=status.HTTP_204_NO_CONTENT)

actor/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from django.http.response import JsonResponse
from django.contrib import messages
from .models import Actor
from .forms import ActorForm


def actor_list(request):
    actors = Actor.objects.all()
    return render(request, 'actor/list.html', context={'actors': actors})


def actor_add(request):
    if request.method == 'GET':
        form = ActorForm()
        return render(request, template_name='actor/add.html', context={'form': form})
    elif request.method == 'POST':
        form = ActorForm(request.POST or None, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse('actor:list'))


def actor_detail(request, **kwargs):
    actor_index = kwargs.get('actor_index')
    actor = Actor.objects.get(id=actor_index)
    return render(request, 'actor/details.html', context={'actor': actor, 'actor_index': actor_index})


def actor_edit(request, **kwargs):
    actor_index = kwargs.get('actor_index')
    actor = Actor.objects.get(id=actor_index)
    if request.method == 'GET':
        form = ActorForm(instance=actor)
        return render(request, template_name='actor/edit.html', context={'form': form, 'actor': actor})
    elif request.method == 'POST':
        form = ActorForm(request.POST or None,
                         files=request.FILES, instance=actor)
        if form.is_valid():
            form.save()
            return redirect(reverse('actor:list'))


def actor_delete(request, **kwargs):
    actor_index = kwargs.get('actor_index')
    actor = Actor.objects.get(id=actor_index)
    actor.delete()
    return redirect(reverse('actor:list'))

actor/templates/actor/add.html
{% extends 'general_templates/base.html' %} {% load crispy_forms_tags %}
{% block body_content %}
<form
  class="d-flex flex-column mx-auto w-50"
  action="{% url 'actor:add' %}"
  method="POST"
  enctype="multipart/form-data"
>
  <h2 class="text-center my-3">Add Actor</h2>
  {% csrf_token %} {{form | crispy}}
  <button type="submit" class="btn btn-success align-self-start my-2">Create</button>
</form>

{% endblock %}

actor/templates/actor/details.html
{% extends 'general_templates/base.html' %} {% block body_content %}
<div class="delete_div d-flex flex-column">
  <div style="color: rgb(225, 225, 225)" class="text-center h3">
    Actor Details.
  </div>
  <div class="w-50 m-auto">
    <img src="{{request.scheme}}://{{request.get_host}}{{actor.profile_picture.url}}"/>
    <br/>
    <div style="color: rgb(225, 225, 225)" class="h5">
      Actor ID : {{ actor_index }}
    </div>
    <div style="color: rgb(225, 225, 225)" class="h5">
      Actor Name : {{ actor.name }}
    </div>
    <div style="color: rgb(225, 225, 225)" class="h5">
      Actor Gender : {{ actor.gender }}
    </div>
    <a class="btn btn-success my-2" href="{% url 'actor:list' %}">Back Home</a>
  </div>
</div>

{% endblock %}

actor/templates/actor/edit.html
{% extends 'general_templates/base.html' %}
{% load crispy_forms_tags %}
{% block body_content %}
<form
  class="d-flex flex-column mx-auto w-50"
  action="{% url 'actor:edit' actor.id%}"
  method="POST"
  enctype="multipart/form-data"
>
  <h2 class="text-center my-3">Edit Actor</h2>
  {% csrf_token %}
  {{form|crispy}}
  <div class="d-flex justify-content-between">
    <a class="btn btn-danger mt-4" href="{% url 'actor:list' %}">Back Home</a>
    <button class="btn btn-success mt-4">Confirm Edit</button>
  </div>
</form>

{% endblock %}

actor/templates/actor/list.html
{% extends 'general_templates/base.html' %} {% block body_content %}
<div class="w-75 m-auto">
  {% if messages %} {% for message in messages %}
  <div class="alert alert-danger" role="alert">{{ message }}</div>
  {% endfor %} {% endif %}
  <div class="d-flex justify-content-center">
    <table class="table table-bordered table-dark">
      <thead>
        <tr>
          <th colspan="4" class="text-center h4">Actors</th>
        </tr>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Actor Name</th>
          <th scope="col">Profile Picture</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      {% for actor in actors %}
      <tr scope="row">
        <td>{{ actor.id }}</td>
        <td>{{ actor.name }}</td>
        <td>
          <img
            style="height: 100px"
            src="{{request.scheme}}://{{request.get_host}}{{actor.profile_picture.url}}"
          />
        </td>
        <td>
          <a
            href="{% url 'actor:details' actor.id%}"
            class="btn btn-primary btn-sm mx-1 my-1"
          >
            Details
          </a>
          {% if request.user.is_authenticated %}
          <a
            href="{% url 'actor:edit' actor.id%}"
            class="btn btn-warning btn-sm mx-1 my-1"
          >
            Edit
          </a>
          <a
            href="{% url 'actor:delete' actor.id%}"
            class="btn btn-danger btn-sm mx-1 my-1"
          >
            Delete
          </a>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </table>
  </div>
  <div class="d-flex justify-content-end">
    <a class="btn btn-success btn-sm mx-1 my-1" href="{% url 'actor:add' %}"
      >Add New Actor</a
    >
  </div>
</div>
{% endblock %}