actor/urls.py
from django.urls import path
from . import views

app_name = 'actor'

urlpatterns = [
    path('add', views.actor_add, name='add'),
    path('details/<int:actor_index>', views.actor_detail, name='details'),
    path('edit/<int:actor_index>', views.actor_edit, name='edit'),
    path('delete/<int:actor_index>', views.actor_delete, name='delete'),
    path('', views.actor_list, name='list'),
]

director/urls.py
from django.urls import path
from . import views

app_name = 'director'

urlpatterns = [
    path('add', views.director_add, name='add'),
    path('details/<int:director_index>', views.director_detail, name='details'),
    path('edit/<int:director_index>', views.director_edit, name='edit'),
    path('delete/<int:director_index>', views.director_delete, name='delete'),
    path('', views.director_list, name='list'),
]

templates/general_templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} App Base page title {% endblock %}</title>
    <style>
      body * {
        color: rgb(220, 220, 220);
      }
    </style>
    <link
      href="{% static 'generic_static/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />
  </head>
  <script src="{% static 'generic_static/js/bootstrap.bundle.min' %}"></script>
  <body style="background-color: black">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'actor:list' %}">Lab 2</a>
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'actor:list' %}"
                >Actors</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'director:list' %}"
                >Director</a
              >
            </li>
          </li>
          </ul>
          <div class="d-flex">
            {% if request.user.is_authenticated %}
            <div class="d-flex align-self-center">Hello {{user.username}}</div>
            <a class="btn btn-danger mx-2" href="{% url 'logout' %}" >Logout</a>
            {% else %}
            <a class="btn btn-success mx-2" href="{% url 'login' %}" >Login</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    {% block body_content %} {% endblock %}
  </body>
</html>