actor/urls.py
from django.urls import path
from . import views

app_name = 'actor'

urlpatterns = [
    path('add', views.actor_add, name='add'),
    path('details/<int:actor_index>', views.actor_detail, name='details'),
    path('edit/<int:actor_index>', views.actor_edit, name='edit'),
    path('delete/<int:actor_index>', views.actor_delete, name='delete'),
    path('', views.actor_list, name='list'),
]

billing/urls.py
from django.urls import path
from . import views

app_name = 'billing'

urlpatterns = [
    path('add', views.billing_add, name='add'),
    path('details/<int:billing_index>', views.billing_detail, name='details'),
    path('edit/<int:billing_index>', views.billing_edit, name='edit'),
    path('done/<int:billing_index>', views.billing_done, name='done'),
    path('delete/<int:billing_index>', views.billing_delete, name='delete'),
    path('', views.billing_list, name='list'),
]

billing/models.py
from django.db import models

class Billing(models.Model):
    pass

billing/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from django.http.response import JsonResponse
from django.contrib import messages
from .models import Billing

billings = Billing.objects.all()


def billing_list(request):
    return render(request, 'billing/list.html', context={'billings': billings})


def billing_add(request):
    if request.method == 'GET':
        return render(request, 'billing/add.html')
    elif request.method == 'POST':
        new_task_index = list(billings)[-1]+1
        new_task_name = request.POST.get('task_name')
        new_task_notes = request.POST.get('task_notes')
        billings[new_task_index] = {"name": new_task_name,
                                    "notes": new_task_notes, "done": False}
        return redirect(reverse('billing:list'))


def billing_detail(request, **kwargs):
    billing_index = kwargs.get('billing_index')
    billing = billings[billing_index]
    return render(request, 'billing/details.html', context={'billing': billing, 'billing_index': billing_index})


def billing_edit(request, **kwargs):
    if request.method == 'GET':
        billing_index = kwargs.get('billing_index')
        billing = billings[billing_index]
        return render(request, 'billing/edit.html', context={'billing': billing, 'billing_index': billing_index})
    elif request.method == 'POST':
        edited_task_index = int(request.POST.get('task_index'))
        edited_task_name = request.POST.get('task_name')
        edited_task_notes = request.POST.get('task_notes')
        billings[edited_task_index] = {"name": edited_task_name,
                                       "notes": edited_task_notes, "done": False}
        return redirect(reverse('billing:list'))


def billing_delete(request, **kwargs):
    billing_index = kwargs.get('billing_index')
    for index, billing in billings.items():
        if index == billing_index:
            if billing['done'] == True:
                billings.pop(billing_index)
            else:
                messages.error(
                    request, "Can't delete a task that is not marked done!")
            break

    return redirect(reverse('billing:list'))


def billing_done(request, **kwargs):
    billing_index = kwargs.get('billing_index')
    billing = billings[billing_index]
    billing['done'] = True if billing['done'] == False else False
    return redirect(reverse('billing:list'))

billing/templates/billing/add.html
{% extends 'general_templates/base.html' %} {% block body_content %}
<form
  class="CRUD_departments d-flex flex-column mx-auto w-50"
  action="{% url 'billing:add' %}"
  method="POST"
>
  {% csrf_token %}
  <div class="input_div">
    <h2 class="text-center mb-5">Add Billing</h2>
    <div
      class="d-flex justify-content-between input_row"
      style="color: rgb(225, 225, 225)"
    >
      <label>Billing Name</label>
      <input
        name="billing_name"
        type="text"
        class="bg-dark text-white"
        placeholder="Enter Billing"
      />
    </div>
    <div
      class="d-flex justify-content-between input_row"
      style="color: rgb(225, 225, 225)"
    >
      <label>Billing Notes</label>
      <input
        name="billing_notes"
        type="text"
        class="bg-dark text-white"
        placeholder="Enter Billing Notes"
      />
    </div>
  </div>
  <div class="d-flex justify-content-between">
    <a class="btn btn-danger mt-4" href="{% url 'billing:list' %}">Back Home</a>
    <button class="btn btn-success mt-4">Confirm Add</button>
  </div>
</form>

{% endblock %}

billing/templates/billing/details.html
{% extends 'general_templates/base.html' %} {% block body_content %}
<div class="delete_div d-flex flex-column">
  <div style="color: rgb(225, 225, 225)" class="text-center h3">
    Billing Details.
  </div>
  <div class="w-50 m-auto">
    <div style="color: rgb(225, 225, 225)" class="h5">
      Billing ID : {{ billing_index }}
    </div>
    <div style="color: rgb(225, 225, 225)" class="h5">
      Billing Name : {{ billing.name }}
    </div>
    <div style="color: rgb(225, 225, 225)" class="h5">
      Billing Notes : {{ billing.notes }}
    </div>
    <div style="color: rgb(225, 225, 225)" class="h5">
      Billing Done : {{ billing.done }}
    </div>
    <a class="btn btn-success my-2" href="{% url 'billing:list' %}">Back Home</a>
  </div>
</div>

{% endblock %}

billing/templates/billing/edit.html
{% extends 'general_templates/base.html' %} {% block body_content %}
<form
  class="CRUD_departments d-flex flex-column mx-auto w-50"
  action="{% url 'billing:edit' billing_index%}"
  method="POST"
>
  {% csrf_token %}
  <div class="input_div">
    <h2 class="text-center mb-5">Edit Billing</h2>
    <div
      class="d-flex justify-content-between input_row"
      style="color: rgb(225, 225, 225)"
    >
      <input name="billing_index" type="text" class="d-none" value="{{billing_index}}" />
      <label>Billing Name</label>
      <input
        name="billing_name"
        type="text"
        class="bg-dark text-white"
        value="{{ billing.name }}"
      />
    </div>
    <div
      class="d-flex justify-content-between input_row"
      style="color: rgb(225, 225, 225)"
    >
      <label>Billing Notes</label>
      <input
        name="billing_notes"
        type="text"
        class="bg-dark text-white"
        value="{{ billing.notes }}"
      />
    </div>
  </div>
  <div class="d-flex justify-content-between">
    <a class="btn btn-danger mt-4" href="{% url 'billing:list' %}">Back Home</a>
    <button class="btn btn-success mt-4">Confirm Edit</button>
  </div>
</form>

{% endblock %}

billing/templates/billing/list.html
{% extends 'general_templates/base.html' %} {% block body_content %}
<div class="w-75 m-auto">
  {% if messages %} {% for message in messages %}
  <div class="alert alert-danger" role="alert">{{ message }}</div>
  {% endfor %} {% endif %}
  <div class="d-flex justify-content-center">
    <table class="table table-bordered table-dark">
      <thead>
        <tr>
          <th colspan="5" class="text-center h4">To Do App</th>
        </tr>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Billing Name</th>
          <th scope="col">Billing Notes</th>
          <th scope="col">Done</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      {% for index, billing in billings.items %}
      <tr scope="row">
        <td>{{ index }}</td>
        <td>{{ billing.name }}</td>
        <td>{{ billing.notes }}</td>
        <td>{{ billing.done }}</td>
        <td>
          <a
            href="{% url 'billing:details' index%}"
            class="btn btn-primary btn-sm mx-1 my-1"
          >
            Details
          </a>
          <a
            href="{% url 'billing:edit' index%}"
            class="btn btn-warning btn-sm mx-1 my-1"
          >
            Edit
          </a>
          <a
            href="{% url 'billing:done' index%}"
            class="btn btn-secondary btn-sm mx-1 my-1"
          >
            Toggle Done
          </a>
          <a
            href="{% url 'billing:delete' index%}"
            class="btn btn-danger btn-sm mx-1 my-1"
          >
            Delete
          </a>
        </td>
      </tr>
      {% endfor %}
    </table>
  </div>
  <div class="d-flex justify-content-end">
    <a class="btn btn-success btn-sm mx-1 my-1" href="{% url 'billing:add' %}"
      >Add New Billing</a
    >
  </div>
</div>
{% endblock %}